### ISSUE TITLE
about releasing code

### ISSUE THREAD

**Issue by XiaoyuShi97** [littlespray/SKFlow#1]
Hi, nice work! I wonder when you plan to release the code. Thx!

**Comment by littlespray** [comment]
Hi Xiaoyu,

Very sorry for the delay. The code is now released at https://github.com/littlespray/SKFlow. Thank you for your interest in our work!

With regard,
Shangkun
[https://opengraph.githubassets.com/bddb480542f764b9bb0797dadd3d67ac83c3375e9899bbba7b64181a3b607978/littlespray/SKFlow]<https://github.com/littlespray/SKFlow>
GitHub - littlespray/SKFlow: This repository is the official implementation of "SKFlow: Learning Optical Flow with Super Kernels"<https://github.com/littlespray/SKFlow>
A tag already exists with the provided branch name. Many Git commands accept both tag and branch names, so creating this branch may cause unexpected behavior.
github.com


________________________________
发件人: Xiaoyu Shi ***@***.***>
发送时间: 2022年9月27日 12:54
收件人: littlespray/SKFlow ***@***.***>
抄送: Subscribed ***@***.***>
主题: [littlespray/SKFlow] about releasing code (Issue #1)


Hi, nice work! I wonder when you plan to release the code. Thx!

―
