### ISSUE TITLE
What is the iters for Sintel and KITTI training and testing datasets?

### ISSUE THREAD

**Issue by Orange066** [littlespray/SKFlow#3]
Hi!

Can share the iters for Sintel and KITTI training and testing datasets when running the evaluate.py? For the example of RAFT, the iters of Sintel and KITTI training dataset is 32 and 24, and the iters of Sintel and KITTI testing datasets is also 32 and 24.

**Comment by Orange066** [comment]
In addition, can you share the pretrained model trained only by C+T data?

**Comment by littlespray** [comment]
Hello, 

Thank you for your interest in our work. We finally set it to 12 for the Sintel training and test sets. For KITTI, it is 18. The pre-trained model by C+T data is available at [here](https://drive.google.com/file/d/18NuBPV4hjivnPsPHPTEbjdiACfqg30Al/view?usp=sharing).

**Comment by Orange066** [comment]
Thanks!
