### ISSUE TITLE
how to install depthwise-conv2d-implicit-gemm==0.0.0

### ISSUE THREAD

**Issue by glfdd** [littlespray/SKFlow#5]
ERROR: unknown command "depthwise-conv2d-implicit-gemm"

**Comment by littlespray** [comment]
Hello,

This package is optional and our code actually does not use it. Thank you for your question and I have delete this package in the requirements.txt. You could also refer to [here](https://github.com/MegEngine/cutlass/tree/master/examples/19_large_depthwise_conv2d_torch_extension) and install it for better efficiency, as mentioned in RepLKNet. Sorry for any inconvenience.
